<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


<h3> Get to Know a numpy Array </h3>


You will use the numpy array <code> A</code> for the following 


In [2]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])

1) Type using the function type 


In [3]:
type(A)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(A)
```

</details>


2) The shape of the array 


In [5]:
A.shape

(3, 2)

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>


3) The type of data in the array 


In [6]:
A.dtype

dtype('int32')

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>


4) Find the second row of the numpy array <code>A</code>:


In [7]:
A[1]

array([21, 22])

<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>


<h3> Two kinds of Multiplying  </h3>


You will use the following numpy arrays for the next questions: 


In [8]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) Multiply array <code> A </code> and <code>B</code>


In [11]:
A * B

C = A * B
C

array([[11,  0],
       [ 0, 22]])

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>


2)  Perform matrix multiplication on array <code> A</code> and <code> B</code> (order will not matter in this case) 


In [12]:
#matrix multiplication where you multiply the row by the column = dot multiplication
Z = np.dot(A,B)
Z

array([[11, 12],
       [21, 22]])

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>


<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
